version: 2.1
nightly:
     triggers:
       - schedule:
           filters:
             branches:
               only:
                 - dev
jobs:
  build:
    docker:
      - image: circleci/node:16.2.4 # the primary container, where your job's commands are run
    steps:
        - add_ssh_keys:
            fingerprints:
              - "ef:94:ff:73:37:a9:7b:ff:29:23:6e:53:40:92:14:0e"
        - checkout
        - run:
            name: Install
            command: yarn install
        - run: 
            name: Build
            command: yarn build
