version: 2          
jobs:
  build:
    docker:
      - image: circleci/node:12 # the primary container, where your job's commands are run
    branches:
      only:
        - dev
    steps:
        - add_ssh_keys:
            fingerprints:
              - "ef:94:ff:73:37:a9:7b:ff:29:23:6e:53:40:92:14:0e"
        - checkout
        - run:
            name: Install
            command: yarn install
        - run: 
            name: Build
            command: yarn build
